v5: rewrite core as a ruby script
This implementation is a lot slower, but no longer depends on deprecated
methods.

We might end up later in a situation where ruby is also deprecated, but the
use case is homebrew integration, so, we assume homebrew installed a usable
ruby.

diff --git a/bin/openssl-osx-ca b/bin/openssl-osx-ca
--- a/bin/openssl-osx-ca
+++ b/bin/openssl-osx-ca
@@ -37,55 +37,49 @@ if [[ ! -x "${brew}" ]]; then
 	exit 1
 fi
 
-exitcode=0
-err() {
-	if [[ -d $1 ]]; then
-		rm -r "${1}"
-	fi
-
-	exitcode=$(($exitcode + 1))
-}
 
 genbundle() {
-	local sslimpl=$1
+	local sslimpl="$1"
+	local certpem="$2"
 
 	local list=$("$brew" list $sslimpl 2>/dev/null)
 	[[ -z $list ]] && continue
 
 	local openssl=$(echo "$list" | grep bin/openssl | head -n 1)
 
-	[[ "${openssl}" = "" ]] && echo "Homebrew $sslimpl not found" && err && return 1
+	[[ "${openssl}" = "" ]] && echo "Homebrew $sslimpl not found" && return 1
 
 	local openssldir=$($openssl version -d | cut -d '"' -f 2)
 
-	[[ "${openssldir}" = "" ]] && echo "$sslimpl directory not found" && err && return 1
+	[[ "${openssldir}" = "" ]] && echo "$sslimpl directory not found" && return 1
 
-	local tmpdir=$(/usr/bin/mktemp -d -t openssl_osx_ca)
-
-	[[ "${tmpdir}" = "" ]] && echo "mktemp failed" && err "${tmpdir}" && return 1
-
-	local certs="${tmpdir}/cert.pem"
-	$osx_ca_certs > $certs
-
-	d1=$($openssl md5 ${openssldir}/cert.pem | awk '{print $2}')
-	d2=$($openssl md5 ${tmpdir}/cert.pem | awk '{print $2}')
+	d1=$($openssl md5 "${openssldir}/cert.pem" | awk '{print $2}')
+	d2=$($openssl md5 "${certpem}" | awk '{print $2}')
 
 	if [[ "${d1}" = "${d2}" ]]; then
 		logger -t "$(basename $0)" "${openssldir}/cert.pem up to date"
 	else
-		# XXX: I don't think this is atomic on OSX, but it's as close as we're going to
-		# get without a lot more work.
-		mv -f ${tmpdir}/* ${openssldir}/
+		cp "${certpem}" "${openssldir}/cert.pem.new"
+		mv -f "${openssldir}/cert.pem"{.new,}
 
 		logger -t "$(basename $0)" "${openssldir}/cert.pem updated"
 	fi
 
-	rm -r "${tmpdir}"
+	return 0
 }
 
-impls="$("$brew" list | grep -E '^((libre|open)ssl(@[0-9\.]+)?)$')"
-for sslimpl in $impls; do
-	genbundle $sslimpl
+
+tmpdir=$(/usr/bin/mktemp -d -t openssl_osx_ca)
+[[ "${tmpdir}" = "" ]] && echo "mktemp failed" && exit 1
+trap 'rm -r "${tmpdir}"' EXIT
+certs="${tmpdir}/cert.pem"
+"${osx_ca_certs}" > "${certs}"
+
+exitcode=0
+impls=($("$brew" list | grep -E '^((libre|open)ssl(@[0-9\.]+)?)$'))
+for sslimpl in "${impls[@]}"; do
+	genbundle "${sslimpl}" "${certs}"
+	exitcode=$(( $exitcode + $? ))
 done
 
 exit $exitcode
